<?php
/**
 * @file slideshow_demo.module
 *
 * Implements an AngularJS-driven block.
 */

/**
 * Implements hook_block_info().
 */
function slideshow_demo_block_info() {
  $blocks['Slideshow Demo'] = array(
    'info' => t('Slideshow Demo'),
  );

  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function slideshow_demo_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'Slideshow Demo':
      $path = drupal_get_path('module', 'slideshow_demo');
      $block['subject'] = t('Slideshow Demo');
      $block['content'] = array(
        '#theme' => 'slideshow_demo',
        '#attached' => array(
          'js' => array(
            'https://ajax.googleapis.com/ajax/libs/angularjs/1.3.7/angular.js',
            $path . '/js/slideshow_demo.js',

          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function slideshow_demo_theme() {
  return array(
    'slideshow_demo' => array(
      'template' => 'slideshow_demo',
      'variables' => array(),
    ),
  );
}